name: start
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:  
  internet_connection_checker: ^1.0.0+1
  get_it: ^7.7.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  shared_preferences: ^2.2.3
  flutter_bloc: ^8.1.5
  bloc_concurrency: ^0.2.5
  font_awesome_flutter: ^10.2.1
  #assets_audio_player: ^3.0.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - C:/Users/Ali Hassn/Desktop/start/lib/features/assets/Maintenance-cuate.png
    - C:/Users/Ali Hassn/Desktop/start/lib/features/assets/Sign in-pana.png
